### ISSUE TITLE
Deploy the Docker image on GKE

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/ml-deployment-k8s-fastapi#6]

**Comment by deep-diver** [comment]
cloud build scripts to push docker image to GCR

```yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/{PROJECT_ID}/{IMAGE_ID}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/{PROJECT_ID}/{IMAGE_ID}']
```

then run `gcloud builds submit --config {PATH}/script.yaml`

**Comment by sayakpaul** [comment]
Would configurations do `script.yaml` specify in this case?

**Comment by deep-diver** [comment]
@sayakpaul yup. the file name is just an example.

here are the scripts for GKE. I have seen `Welcome!` message successfully from the fastAPI server.

Both k8s objects are created by the following commands respectively.
```shell
$ kubectl create deployment fastapi-server \
                            --image=gcr.io/gcp-ml-172005/k8s-fastapi \
                            --dry-run=client \
                            --output=yaml > deployment.yaml

$ kubectl expose deployment fastapi-server \
                            --type LoadBalancer \
                            --port 80 \
                            --target-port 8080 \
                            --dry-run=client \
                            --output=yaml > service.yaml
```

Deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi-server
    spec:
      containers:
      - image: gcr.io/{PROJECT_ID}/{IMAGE_ID}
        name: {IMAGE_ID}
        ports:
        - containerPort: 80          
        resources: {}
status: {}
```

Service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-server
  name: fastapi-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastapi-server
  type: LoadBalancer
status:
  loadBalancer: {}
```
